<?php
$arrPoints = array(
    '听力' => array(
        '听力' => array(),
    ),
    '词汇' => array(
        '单词、词组' => array(),
        '语音' => array(),
    ),
    '语法' => array(
        '名词' => array(
            '可数名词及单复数' => array(),
            '不可数名词' => array(),
            '专有名词' => array(),
            '集合名词' => array(),
            '名词所有格' => array(),
            '名词' => array(),
        ),
        '冠词' => array(
            '不定冠词' => array(),
            '定冠词' => array(),
            '零冠词' => array(),
        ),
        '数词' => array(
            '基数词' => array(),
            '序数词' => array(),
            '小数' => array(),
            '分数' => array(),
        ),
        '量词' => array(
            '量词' => array(),
        ),
        '代词' => array(
            '物主代词' => array(),
            '反身代词' => array(),
            '相互代词' => array(),
            '指示代词' => array(),
            '疑问代词' => array(),
            '不定代词' => array(),
            '连接代词' => array(),
            '关系代词' => array(),
        ),
        '形容词' => array(
            '形容词比较及' => array(),
            '形容词最高级' => array(),
            '形容词排序' => array(),
            '形容词' => array(),
        ),
        '副词' => array(
            '副词比较及' => array(),
            '副词最高级' => array(),
            '时间' => array(),
            '地点副词' => array(),
            '方式副词' => array(),
            '程度副词' => array(),
            '疑问副词' => array(),
            '频度副词' => array(),
            '连接副词' => array(),
            '关系副词' => array(),
            '副词' => array(),
        ),
        '介词和介词短语' => array(
            '介词和介词短语' => array(),
        ),
        '连词' => array(
            '并列连词' => array(),
            '丛书连词' => array(),
        ),
        '动词' => array(
            '动词第三人称单数' => array(),
            '动词过去式' => array(),
            '动词现在分词' => array(),
            '动词过去分词' => array(),
            '系动词' => array(),
            '情态动词' => array(),
            '助动词' => array(),
            '动词短语' => array(),
            '动词' => array(),
        ),
        '非谓语动词' => array(
            '分词' => array(
                '现在分词' => array(),
                '过去分词' => array(),
            ),
            '动名词' => array(
                '主语' => array(
                    '语法填空' => array(),
                    '完形填空' => array(),
                    '单项选择' => array(),
                ),
                '宾语' => array(
                    '语法填空' => array(
                        '介词宾语' => array(),
                        '动词宾语' => array(),
                    ),
                    '完形填空' => array(),
                ),
            ),
            '不定式' => array(
                '主语' => array(
                    '语法填空' => array(),
                ),
                '宾语' => array(),
            ),
        ),
        '时态' => array(
            '一般现在时' => array(),
            '一般过去时' => array(),
            '一般将来时' => array(),
            '现在进行时' => array(),
            '过去进行时' => array(),
            '过去将来时' => array(),
            '将来进行时' => array(),
            '现在完成时' => array(),
            '过去完成时' => array(),
            '现在完成进行时' => array(),
            '将来完成时' => array(),
            '过去完成进行时' => array(),
        ),
        '被动语态' => array(
            '一般将来时被动语态' => array(),
            '现在完成时被动语态' => array(),
            '现在进行时被动语态' => array(),
            '一般过去时被动语态' => array(),
            '过去完成的被动语态' => array(),
            '一般现在时被动语态' => array(),
            '过去进行时被动语态' => array(),
            '将来完成时的被动语态' => array(),
            '过去将来时的被动语态' => array(),
        ),
        '句子' => array(
            '肯定句' => array(),
            '全部否定' => array(),
            '部分否定' => array(),
            '一般疑问句' => array(),
            '特殊疑问句' => array(),
            '选择疑问句' => array(),
            '反意疑问句' => array(),
            '祈使句' => array(),
            '感叹句' => array(),
            '状语从句' => array(),
            '限制性定语从句' => array(),
            '非限制性定语从句' => array(),
            '主语从句' => array(),
            '宾语从句' => array(),
            '表语从句' => array(),
            '同位语从句' => array(),
            '全部倒装' => array(),
            '部分倒装' => array(),
            '强调句' => array(),
            '省略句' => array(),
            '插入语' => array(),
            'it 的用法' => array(),
            'there be 句型' => array(),
            '主谓一致' => array(),
            '虚拟语气' => array(),
            '独立主格结构' => array(),
            '直接引语与间接引语' => array(),
            '反诘句' => array(),
        ),
        '构词法' => array(
            '合成法' => array(),
            '派生法' => array(),
            '转化法' => array(),
            '缩写与简写' => array(),
        ),
    ),
    '情景交际' => array(
        '日常用语，谚语' => array(),
        '情景交际' => array(),
    ),
    '阅读能力' => array(
        '人物传记类阅读' => array(),
        '故事类阅读' => array(),
        '广告布告类阅读' => array(),
        '新闻报道类阅读' => array(),
        '科教类阅读' => array(),
        '社会现象类阅读' => array(),
        '政治经济类阅读' => array(),
        '历史文化类阅读' => array(),
        '日常生活类阅读' => array(),
        '健康环保类阅读' => array(),
        '人生感悟类阅读' => array(),
    ),
    '翻译能力' => array(
        '翻译能力' => array(),
    ),
    '写作能力' => array(
        '小作文' => array(),
        '大作文' => array(
            '提纲作文' => array(),
            '图表作文' => array(),
            '图画作文' => array(),
        ),
    ),
);

